# Generated by Django 4.1.6 on 2023-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_students_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='courses.courses'),
        ),
    ]
